name: ${COMPOSE_PROJECT_NAME}
services:
  webserver:
    build: ./webserver
    container_name: webserver
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ../app/public:/var/www/html/public:ro
    depends_on:
      - app
    networks:
      - bugtracker

  app:
    build: ./app
    container_name: application
    env_file:
      - .env
    volumes:
      - ../app:/var/www/html
    depends_on:
      - db
    networks:
      - bugtracker

  db:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bugtracker

  websocket:
    build: ./websocket
    container_name: websocket
    volumes:
      - ../app:/var/www/html
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - bugtracker

  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - bugtracker

networks:
  bugtracker:

volumes:
  db-data:
